sudo: false
language: node_js
before_install:
  - gem install sass compass
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'grunt build'
